on:
  schedules:
    - cron: '*/10 * * * *'
name: Update gist with WakaTime stats
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: update-gist
        uses: FlorentF9/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e2cf6ae805e614e18d2269eb40ad39ab
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
